### ISSUE TITLE
Day 2

### ISSUE THREAD

**Issue by Severrinn** [dlab-berkeley/R-Fundamentals#10]
Poll 2-1 is missing from the R zoom meeting template. It needs to be added in. @aculich What is the default SPA zoom account for R workshops.

**Comment by heroashman** [comment]
It was in but not "enabled" - I have enabled it but not sure if there is something more long term that needs doing.

**Comment by heroashman** [comment]
Aaron is enabling all the polls going forward in spa-2. Will resolve this issue once that is confirmed.
