### ISSUE TITLE
Part 3: Small grammatical issues here and there

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/R-Fundamentals#12]
There are a smattering of very small grammatical issues/typos in Part 3. It's worth going through it to try and get all of them.

Here are a couple examples:

"Before we get started, lets load in the..."
"In Part 2 we learned to read in a csv file and assign it to a data frame called gap. Lets do that again."

**Comment by heroashman** [comment]
Fixed these and other grammar issues that showed up when pasting the contents into Word (I am a very bad speller and R has a terrible spellcheck)
