### ISSUE TITLE
Part 4 - solutions

### ISSUE THREAD

**Issue by heroashman** [dlab-berkeley/R-Fundamentals#14]
In challenge 4 we reference logging one of the variables but do not provide information about what logging is. Should provide a link to what it means to log a variable (can also consider providing link to longer more detailed discussing on StackOverflow about *when* to log a variable: https://stats.stackexchange.com/questions/298/in-linear-regression-when-is-it-appropriate-to-use-the-log-of-an-independent-va)

**Comment by mingyu-yuan** [comment]
add myself to this issue

**Comment by heroashman** [comment]
I've added text into the solutions about what logging is.
