### ISSUE TITLE
Add to input warning in Lesson 2

### ISSUE THREAD

**Issue by ldliao** [dlab-berkeley/R-Fundamentals#29]
line 84

⚠️ **Warning:** Not all functions have inputs or arguments - for example, the `ls()` function doesn't require an input but still gives us an output.

should also include a warning for not all function has an output (with example)

**Comment by heroashman** [comment]
@ldliao Good idea! What is an example of this? I can't think of a function that would come up in R fundamentals that doesn't have an output

**Comment by ldliao** [comment]
@pssachdeva did you have a specific example you wanted to mention or just the warning to be included?

**Comment by pssachdeva** [comment]
You can do `rm()` which is covered in that same section
