### ISSUE TITLE
mean function comment in Part 4

### ISSUE THREAD

**Issue by ldliao** [dlab-berkeley/R-Fundamentals#30]
majority of the lesson uses the pipe operator
not sure if we want to use the `pull` function for the `mean` function or `summarize` to make it more in sync

**Comment by heroashman** [comment]
@ldliao what code lines are you looking at for this? I'm not sure I follow where it is. Thanks!

**Comment by ldliao** [comment]
an example: instead of `mean(gap$lifeExp)` do `gap %>% pull(lifeExp) %>% mean()` or other ways to write this

**Comment by heroashman** [comment]
Got it! Thanks. I've updated it
