### ISSUE TITLE
Part 2 - potentially add data frame indexing example

### ISSUE THREAD

**Issue by alexramiller** [dlab-berkeley/R-Fundamentals#43]
Line 317: notebook currently mentions that you can use numeric indexing with the [row,column] format to subset a dataframe, but doesn't show any examples of what this looks like. Recommend adding in a code chunk that gives a few examples, which could look something like:

```
# extract the first value of the first column
gap[1,1]

# extract the entire first row
gap[1,]

# extract the entire third column
gap[,3]
```

**Comment by heroashman** [comment]
Added - thanks for the example!
